import type { Meeting, Speaker, Summary, Transcript } from '@huilu/core'
import { formatTimestamp } from './transcript'

/** 交给大模型的逐字稿：每行「[时间 | 毫秒] 发言人: 文本」，章节的 startMs 直接取方括号里的毫秒数 */
export function buildSummaryPrompt(
  meeting: Pick<Meeting, 'title' | 'durationMs'>,
  transcript: Transcript,
  speakers: Speaker[],
  locale: string,
): string {
  const zh = locale.startsWith('zh')
  const name = new Map(speakers.map((s) => [s.id, s.name]))
  const legend = speakers.map((s) => `- ${s.name}: speakerId = "${s.id}"`).join('\n')
  const lines = transcript.segments
    .map(
      (s) =>
        `[${formatTimestamp(s.startMs)} | ${s.startMs}] ${name.get(s.speakerId) ?? s.speakerId}: ${s.text}`,
    )
    .join('\n')
  const header = zh
    ? [
        `会议名称：${meeting.title || '未命名会议'}`,
        `时长：${formatTimestamp(meeting.durationMs)}`,
        '发言人（speakerSummaries 的 speakerId 必须取下面的值；逐字稿不区分发言人时只有一位）：',
        legend,
        '逐字稿（每行开头方括号内为「时间 | 距开始的毫秒数」，chapters 的 startMs 请直接使用该毫秒数）：',
      ]
    : [
        `Meeting title: ${meeting.title || 'Untitled meeting'}`,
        `Duration: ${formatTimestamp(meeting.durationMs)}`,
        'Speakers (speakerSummaries.speakerId must be one of these values; there is only one when the transcript has no diarization):',
        legend,
        'Transcript (each line starts with "[time | milliseconds from start]"; use that millisecond number for chapters[].startMs):',
      ]
  return [...header, lines].join('\n')
}

/**
 * 大模型的输出只在格式上被 schema 约束，内容上再做一次整理：
 * 章节时间限制在会议时长内并按时间排序，发言总结只保留逐字稿中存在的发言人，去掉空条目
 */
export function normalizeSummary(
  summary: Summary,
  speakers: Speaker[],
  durationMs: number,
): Summary {
  const known = new Set(speakers.map((s) => s.id))
  const max = Math.max(0, durationMs)
  const text = (s: string) => s.trim()
  return {
    keywords: [...new Set(summary.keywords.map(text).filter(Boolean))],
    overview: text(summary.overview),
    chapters: summary.chapters
      .map((c) => ({
        ...c,
        startMs: Math.min(max, Math.max(0, Math.round(c.startMs))),
        title: text(c.title),
        summary: text(c.summary),
      }))
      .filter((c) => c.title || c.summary)
      .sort((a, b) => a.startMs - b.startMs),
    speakerSummaries: summary.speakerSummaries
      .map((s) => ({ ...s, speakerId: String(s.speakerId), summary: text(s.summary) }))
      .filter((s) => known.has(s.speakerId) && s.summary),
    keyPoints: summary.keyPoints.map(text).filter(Boolean),
    actionItems: summary.actionItems
      .map((a) => ({
        text: text(a.text),
        ...(a.owner?.trim() ? { owner: a.owner.trim() } : {}),
        ...(a.due?.trim() ? { due: a.due.trim() } : {}),
      }))
      .filter((a) => a.text),
  }
}

const LABELS = {
  zh: {
    date: '时间',
    duration: '时长',
    keywords: '关键词',
    overview: '全文概要',
    chapters: '章节速览',
    speakers: '发言总结',
    keyPoints: '要点回顾',
    actions: '待办事项',
    owner: '负责人',
    due: '截止',
    none: '无',
    separator: '，',
    listSeparator: '、',
    generated: '由会录 HuiLu 根据逐字稿自动生成，请以原始录音为准。',
  },
  en: {
    date: 'Date',
    duration: 'Duration',
    keywords: 'Keywords',
    overview: 'Overview',
    chapters: 'Chapters',
    speakers: 'Speaker summaries',
    keyPoints: 'Key points',
    actions: 'Action items',
    owner: 'Owner',
    due: 'Due',
    none: 'None',
    separator: ', ',
    listSeparator: ', ',
    generated:
      'Generated by HuiLu from the transcript. Check the original recording when in doubt.',
  },
}

/** summary.md：可直接阅读的纪要，与 summary.json 内容一致 */
export function renderSummaryMarkdown(
  meeting: Pick<Meeting, 'title' | 'createdAt' | 'durationMs'>,
  summary: Summary,
  speakers: Speaker[],
  locale: string,
): string {
  const l = locale.startsWith('zh') ? LABELS.zh : LABELS.en
  const name = new Map(speakers.map((s) => [s.id, s.name]))
  const list = (items: string[]) => (items.length ? items.map((i) => `- ${i}`) : [`- ${l.none}`])
  const created = new Date(meeting.createdAt)
  const pad = (n: number) => String(n).padStart(2, '0')
  const date = `${created.getFullYear()}-${pad(created.getMonth() + 1)}-${pad(created.getDate())} ${pad(created.getHours())}:${pad(created.getMinutes())}`
  return [
    `# ${meeting.title}`,
    '',
    `> ${l.date}: ${date} · ${l.duration}: ${formatTimestamp(meeting.durationMs)}`,
    '',
    `## ${l.keywords}`,
    '',
    summary.keywords.length ? summary.keywords.join(l.listSeparator) : l.none,
    '',
    `## ${l.overview}`,
    '',
    summary.overview || l.none,
    '',
    `## ${l.chapters}`,
    '',
    ...list(
      summary.chapters.map(
        (c) =>
          `\`${formatTimestamp(c.startMs)}\` **${c.title}**${c.summary ? ` — ${c.summary}` : ''}`,
      ),
    ),
    '',
    `## ${l.speakers}`,
    '',
    ...list(
      summary.speakerSummaries.map(
        (s) => `**${name.get(s.speakerId) ?? s.speakerId}**: ${s.summary}`,
      ),
    ),
    '',
    `## ${l.keyPoints}`,
    '',
    ...list(summary.keyPoints),
    '',
    `## ${l.actions}`,
    '',
    ...(summary.actionItems.length
      ? summary.actionItems.map((a) => {
          const meta = [a.owner && `${l.owner}: ${a.owner}`, a.due && `${l.due}: ${a.due}`]
            .filter(Boolean)
            .join(l.separator)
          const suffix = !meta ? '' : locale.startsWith('zh') ? `（${meta}）` : ` (${meta})`
          return `- [ ] ${a.text}${suffix}`
        })
      : [`- ${l.none}`]),
    '',
    '---',
    '',
    `_${l.generated}_`,
    '',
  ].join('\n')
}
